workspace:
  base: /go
  path: src/github.com/andresr19/jenkins101golang

pipeline:
  build:
    image: golang
    commands:
      - go get
      - go build
      - go test
  publish:
    image: plugins/docker
    settings:
      username: ${DOCKER_HUB_USERNAME}
      password: ${DOCKER_HUB_PASSWORD}
      repo: ${DOCKER_HUB_REPONAME}
      tags: 1.0.0