workspace:
  base: /go
  path: src/github.com/andresr19/jenkins101golang

pipeline:
  build:
    image: golang
    commands:
      - go get
      - go build
      - go test
  publish:
    image: plugins/docker
    settings:
      username: 
        from_secret: ${DOCKER_HUB_USERNAME}
      password: 
        from_secret: ${DOCKER_HUB_PASSWORD}
      repo: kkthnxbye/jenkinsgolang101
      auto_tag: true