workspace:
  base: /app
  path: src

pipeline:
  test:
    image: golang
    commands:
      - go get
      - go test
  build:
    image: golang
    commands:
      - go get
      - go build
      - go test