workspace:
  base: /go
  path: src/github.com/andresr19/jenkins101golang

pipeline:
  build:
    image: golang
    commands:
      - go get
      - go build
      - go test
  publish:
    image: plugins/docker
    secrets: [ DOCKER_HUB_USERNAME, DOCKER_HUB_PASSWORD ]
    repo: docker.io/kkthnxbye/jenkinsgolang101
    tags: latest